# See https://gitlab.com/help/ci/quick_start/README
test:
  script:
    - apt-get update -qq
    - apt-get install -y build-essential autoconf automake libtool lsb-release
    - lsb_release -a
    - uname -a
    - ./autogen.sh
    - ./configure
    - make
    - make check
    - make distcheck
