version: 1.0.{build}

os: Visual Studio 2015

platform: x64

configuration: Release

branches:
  only:
    - svn-trunk
    - svn-3.5

shallow_clone: true
clone_depth: 5

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

environment:
  matrix:
    - CFG: Debug
      PLATFORM: Win32
    - CFG: Release
      PLATFORM: Win64

init:
  - ps: |
      Write-Host "Build worker environment variables:" -ForegroundColor Magenta
      Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}

before_build:
  - ps: |
      if ($env:PLATFORM -Match "Win32") {
        $G="Visual Studio 14 2015"
      } elseif ($env:PLATFORM -Match "Win64") {
        $G="Visual Studio 14 2015 Win64"
      }
      Write-Host "Running CMake:" -ForegroundColor Magenta
      cmake.exe -G $G -DCMAKE_BUILD_TYPE=$env:CFG $env:APPVEYOR_BUILD_FOLDER
      Write-Host "Running MSBuild:" -ForegroundColor Magenta
  - ps: 

build:
  parallel: true
  project: GEOS.sln
  verbosity: minimal

test_script:
  - ps: |
      Write-Host "Running CTest:" -ForegroundColor Magenta
      $cmd = 'ctest -V --output-on-failure -C ' + $Env:CFG
      iex "& $cmd"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

# If you need to debug AppVeyor session (https://www.appveyor.com/docs/how-to/rdp-to-build-worker), then:
# 1. Uncomment the on_finish section below:
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# 2. Add this line to the init section below
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
